### ISSUE TITLE
Update documentation and project description for v2 

### ISSUE THREAD

**Issue by psoukie** [psoukie/zipchord#80]
Include description and documentation for: 
- [x] shorthands (#52)
- [x] OSD hints for existing shortcuts (#50)
- [x] More flexible dictionary format (#82)
- [x] Defining new shortcuts (#79)
- [x] #98
- [x] Changes added in later betas and RC's
- [x] UI screenshots
- [x] Animation showing ZipChord in action
